version: '3.7'

services:
  mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_DATABASE: 'bookStore'
      MYSQL_USER: 'samir'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
