spring:
  application:
    name: book-store
  profiles:
    include:
      - security
      - mail
      - db

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
server:
  port: 8080
